create table TB_CLIENTES(
  CLIENTE_ID NUMBER(10),
  NOME VARCHAR2(60),
  CPF VARCHAR2(14),
  ENDERECO VARCHAR2(60),
  BAIRRO VARCHAR2(60),
  CIDADE VARCHAR2(60),
  ESTADO VARCHAR2(2),
  CEP VARCHAR2(10)
);

CREATE SEQUENCE SEQ_TB_CLIENTES
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
